---
- hosts: all
  become: true

  pre_tasks:
    - name: Config
      include_vars: vars.yml

    - name: apt cache update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: apt Upgrade
      apt:
        upgrade: yes
      when:
        - ansible_facts.os_family == "Debian"

    - name: yum cache update & upgrade
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when:
        - ansible_facts.os_family == "RedHat"

  handlers:
    - name: Include handlers
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:

    - name: Install packages/prerequisites
      import_tasks: tasks/packages.yml

    - name: Setup Docker.
      import_tasks: tasks/docker.yml

    - name: Install Nginx Proxy Manager
      import_tasks: tasks/proxy.yml
      when: proxy_enable

    - name: install portainer
      import_tasks: tasks/portainer.yml
      when: portainer_enable

    - name: install pihole
      import_tasks: tasks/pihole.yml
      when: pihole_enable

    - name: cloudflare ddns
      import_tasks: tasks/ddns.yml
      when: cf_ddns_enable
