---

- name: if Docker is already installed?.
  command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_present

- name: Download Docker install script.
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when:
    - docker_present.rc == 1
    - ansible_facts.os_family != "RedHat"

- name: Run Docker install script.
  command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when:
    - docker_present.rc == 1
    - ansible_facts.os_family != "RedHat"

- name: add docker repo to yum
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when:
    - docker_present.rc == 1
    - ansible_facts.os_family == "RedHat"

- name: update yum cache
  yum:
    update_cache: yes
  when:
    - ansible_facts.os_family == "RedHat"
    - docker_present.rc == 1

- name: install docker on redhat
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when:
    - docker_present.rc == 1
    - ansible_facts.os_family == "RedHat"

- name: Start docker
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose using Pip
  ansible.builtin.pip:
    name: docker-compose
    state: present
    executable: pip3

- name: Create group docker
  group:
    name: docker
    state: present

- name: adding existing user '{{ ansible_user }}' to group sudo
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

- name: Reset connection
  meta: reset_connection
