---

- name: Deploy pihole
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:latest
    restart_policy: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "90:80/tcp"
      - "8443:443/tcp"
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    env:
      TZ: "{{ pihole_timezone }}"
      WEBPASSWORD: "{{ pihole_password }}"
      ServerIP: "{{ ansible_facts['default_ipv4']['address'] }}"
    capabilities:
      - NET_ADMIN
    dns_servers:
      - 1.1.1.1
      - 127.0.0.1
