---
- name: Create a network for proxy manager
  community.docker.docker_network:
    name: "{{ network }}"

- name: Nginx Proxy Manager deploy
  community.docker.docker_container:
    name: nginx_proxy
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "/data:/data"
      - "/letsencrypt:/etc/letsencrypt"
    restart_policy: unless-stopped
    networks:
      - name: "{{ network }}"
    network_mode: "{{ network }}"
